language: node_js
node_js:
   - "0.12"
addons:
  postgresql: "9.3"
before_script:
  - psql -c 'create database pg_promise_test;' -U postgres
  - node test/db/init.js
branches:
  only:
    - test_upgrade
